资源加载错误，通过 addEventListener('error', callback, true)在捕获阶段捕捉资源加载失败错误。

js 执行错误，通过 window.onerror 捕捉 js 错误。

跨域的脚本会给出 "Script Error." 提示，拿不到具体的错误信息和堆栈信息。此时需要在 script 标签增加 crossorigin="anonymous"属性，同时资源服务器需要增加 CORS 相关配置，比如 Access-Control-Allow-Origin: \*

promise 错误，通过 addEventListener('unhandledrejection', callback)捕捉 promise 错误，但是没有发生错误的行数，列数等信息，只能手动抛出相关错误信息。

```js
// 在捕获阶段，捕获资源加载失败错误
addEventListener(
  'error',
  (e) => {
    const target = e.target
    if (target != window) {
      monitor.errors.push({
        type: target.localName,
        url: target.src || target.href,
        msg: (target.src || target.href) + ' is load error',
        time: Date.now(),
      })
    }
  },
  true
)

// 监听 js 错误
window.onerror = function (msg, url, row, col, error) {
  monitor.errors.push({
    type: 'javascript',
    row: row,
    col: col,
    msg: error && error.stack ? error.stack : msg,
    url: url,
    time: Date.now(),
  })
}

// 监听 promise 错误 缺点是获取不到行数数据
addEventListener('unhandledrejection', (e) => {
  monitor.errors.push({
    type: 'promise',
    msg: (e.reason && e.reason.msg) || e.reason || '',
    time: Date.now(),
  })
})
```
